# Change these first
owner: icarolosada # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: larakalobarcelona
    url: https://larakalobarcelona.es/
    maxResponseTime: 4000          # (ms) marca como lento si excede
    expectedStatusCodes: [200, 301, 302]  # acepta redirecciones típicas

# === Configuración de la status page (GitHub Pages) ===
status-website:
  # cname: status.larakalobarcelona.es   # Subdominio para tu status page
  # Si NO vas a usar dominio propio, comenta la línea de arriba y descomenta la siguiente con el nombre del repo
  baseUrl: /Uptime

  # Branding (opcional)
  # Cambia el logo si tienes una URL propia (PNG/SVG). Si no, deja el icono por defecto.
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado • Lara Kalo Barcelona
  introTitle: "**Estado del servicio**"
  introMessage: >
    Monitoreo automático de disponibilidad y latencia de **larakalobarcelona.es**.
    Esta página se actualiza en tiempo real con datos generados por GitHub Actions y alojados en GitHub Pages.

  navbar:
    - title: Estado
      href: /
    - title: Web
      href: https://larakalobarcelona.es/
    - title: GitHub
      href: https://github.com/icarolosada/Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
